import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from "react"
import create from "zustand"

interface Pokemon {
  id: number
  name: string
  image: string
}

const usePokemonStore = create <{
  pokemon: Pokemon[], 
  setPokemon: (pokemon: Pokemon[]) => void,
  filteredPokemon: Pokemon[],
  filter: string,
  setFilter: (filter:string) => void,
}> ((set) => ({
  pokemon: [],
  filteredPokemon: [],
  filter: "",
  setPokemon: (pokemon: Pokemon[]) => set({pokemon, filteredPokemon: pokemon}),
  setFilter: (filter: string) => set((state) => ({
    filter,
    filteredPokemon: state.pokemon.filter((pokemon) =>
      pokemon.name.toLowerCase().includes(filter.toLowerCase())
    )
  }))
}))

export async function getServerSideProps() {

  const response = await fetch (
    "https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json"
  )
  usePokemonStore.getState().setPokemon(await response.json())
  return {
    props: {
      pokemon: usePokemonStore.getState().pokemon,
    }
  }
}

export default function Home({pokemon}:{pokemon: Pokemon[]}) {
  const {filter, filteredPokemon, setFilter} = usePokemonStore();

  return(
    <div className={styles.main}>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by Create Next App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <input 
          type="text" 
          value={filter} 
          onChange={(event) => setFilter(event.target.value)}
          className={styles.search}
        />
      </div>
      <div className={styles.container}>
        {filteredPokemon.slice(0,20).map((mapPokemon) => (
          <div key={mapPokemon.id} className={styles.image}>
            <img 
              alt={mapPokemon.name} 
              src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${mapPokemon.image}`}
            />
            <h2>{mapPokemon.name}</h2>
          </div>
        ))}
      </div>
    </div>
  )

}