import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from "react"
export {getServerSideProps} from "../src/contextStore"
import {usePokemon} from "../src/contextStore"

export default function Home() {
  const {pokemon, filter, setFilter} = usePokemon()
  return(
    <div className={styles.main}>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by Create Next App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <input 
          type="text" 
          value={filter} 
          onChange={(event) => setFilter(event.target.value)}
          className={styles.search}
        />
      </div>
      <div className={styles.container}>
        {pokemon.slice(0,20).map((mapPokemon:any) => (
          <div key={mapPokemon.id} className={styles.image}>
            <img 
              alt={mapPokemon.name} 
              src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${mapPokemon.image}`}
            />
            <h2>{mapPokemon.name}</h2>
          </div>
        ))}
      </div>
    </div>
  )

}