/* eslint-disable @next/next/no-img-element */
import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import store, { type Pokemon } from "../src/MobXStore";
import { observer } from "mobx-react-lite";

export async function getServerSideProps() {
  const response = await fetch(
    "https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json"
  );

  store.pokemon = await response.json();

  return {
    props: {
      initialPokemon: store.pokemon,
    },
  };
}

function Home({ initialPokemon }: { initialPokemon: Pokemon[] }) {
  React.useEffect(() => {
    store.pokemon = initialPokemon;
  }, [initialPokemon]);

  return (
    <div className={styles.main}>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <input
          type="text"
          value={store.filter}
          onChange={(event) => (store.filter = event.target.value)}
          className={styles.search}
        />
      </div>
      <div className={styles.container}>
        {store.filteredPokemon.slice(0, 20).map((mapPokemon) => (
          <div key={mapPokemon.id} className={styles.image}>
            <img
              alt={mapPokemon.name}
              src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${mapPokemon.image}`}
            />
            <h2>{mapPokemon.name}</h2>
          </div>
        ))}
      </div>
    </div>
  );
}

export default observer(Home);