import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from "react"
import jotai, {atom, useAtom} from "jotai"
import {useHydrateAtoms} from "jotai/utils"

interface Pokemon {
  id: number
  name: string
  image: string
}

const pokemonAtom = jotai.atom<Pokemon[]>([])
const filterAtom = jotai.atom("")
const filteredPokemon = jotai.atom((get) => 
  get(pokemonAtom).filter((pokemon) =>
    pokemon.name.toLowerCase().includes(get(filterAtom).toLowerCase())
  )
)

export async function getServerSideProps() {
  const response = await fetch (
    "https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json"
  )
  return {
    props: {
      initialPokemon: await response.json()
    }
  }
}

export default function Home({initialPokemon}:{initialPokemon: Pokemon[]}) {

  useHydrateAtoms([[pokemonAtom, initialPokemon]] as const)
  const [pokemon] = jotai.useAtom(filteredPokemon)
  const [filter, setFilter] = jotai.useAtom(filterAtom)

  return(
    <div className={styles.main}>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by Create Next App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <input 
          type="text" 
          value={filter} 
          onChange={(event) => setFilter(event.target.value)}
          className={styles.search}
        />
      </div>
      <div className={styles.container}>
        {pokemon.slice(0,20).map((mapPokemon:any) => (
          <div key={mapPokemon.id} className={styles.image}>
            <img 
              alt={mapPokemon.name} 
              src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${mapPokemon.image}`}
            />
            <h2>{mapPokemon.name}</h2>
          </div>
        ))}
      </div>
    </div>
  )

}